import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * The memos live in /insights at the repo root, not inside site/, because they
 * are generated by the analysis layer and are a deliverable in their own right -
 * readable in the repo without building the site. The glob loader reads them in
 * place rather than duplicating them.
 */
const insights = defineCollection({
  loader: glob({ pattern: '*.md', base: '../insights' }),
  schema: z.object({
    title: z.string(),
    generated: z.coerce.date(),
    generator: z.string(),
    sources: z.array(z.string()).default([]),
  }),
});

export const collections = { insights };
