"""Generate docs/sources.md from the provenance ledger the fetchers write.

CLAUDE.md rule 2 says every figure traces to a source with an access date. That
is only credible if the source list cannot drift from the code, so it is
generated, never hand-written.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / "data-pipeline" / "data" / "processed" / "_provenance.json"
OUT = ROOT / "docs" / "sources.md"
DICT_OUT = ROOT / "docs" / "data-dictionary.md"
PROCESSED = ROOT / "data-pipeline" / "data" / "processed"


# Column-name conventions, so units are never guessed from context.
UNITS = [
    ("_mn", "millions"), ("_bn", "billions"), ("_cr", "INR crore"),
    ("_lakh_cr", "INR lakh crore"), ("_inr", "INR"), ("_pct", "per cent"),
    ("_bps", "basis points"), ("_share", "fraction of total (0-1)"),
    ("_yoy", "year-on-year change (fraction)"), ("hhi", "index, 0-10,000"),
    ("month", "YYYY-MM"), ("period", "YYYYQn"), ("date", "YYYY-MM-DD"),
    ("fy_end", "YYYY-MM-DD (fiscal year end)"), ("count", "transactions"),
]


def unit_for(column: str) -> str:
    low = column.lower()
    for suffix, unit in sorted(UNITS, key=lambda kv: -len(kv[0])):
        if low.endswith(suffix) or low == suffix:
            return unit
    return ""


def build_dictionary(ledger: dict) -> None:
    """Emit docs/data-dictionary.md from the processed files themselves, so a
    renamed or dropped column cannot leave stale documentation behind."""
    import pandas as pd

    lines = [
        "# Data dictionary",
        "",
        "<!-- GENERATED by docs/build_docs.py from the processed files themselves.",
        "     Do not edit by hand: re-run `python docs/build_docs.py`. -->",
        "",
        "Every committed dataset the site and the analysis layer read, with its columns,",
        "types and units. Units are derived from the naming convention (`_mn`, `_cr`,",
        "`_share`, `_bps`, ...), which is why the convention is worth keeping.",
        "",
    ]
    for path in sorted(PROCESSED.glob("*.csv")):
        name = path.stem
        df = pd.read_csv(path, nrows=200)
        full = sum(1 for _ in path.open(encoding="utf-8")) - 1
        meta = ledger.get(name, {})
        lines.append(f"## `{name}`")
        lines.append("")
        if meta:
            lines.append(f"{meta.get('publisher', 'derived')} · {meta.get('coverage', '')} · "
                         f"{full:,} rows · accessed {meta.get('accessed', 'n/a')}")
        else:
            lines.append(f"Derived by the pipeline · {full:,} rows")
        lines.append("")
        lines.append("| Column | Type | Unit | Example |")
        lines.append("|---|---|---|---|")
        for col in df.columns:
            sample = df[col].dropna()
            example = str(sample.iloc[0])[:28] if len(sample) else ""
            lines.append(f"| `{col}` | {df[col].dtype} | {unit_for(col)} | {example} |")
        lines.append("")
    DICT_OUT.write_text(chr(10).join(lines), encoding="utf-8")
    print(f"wrote {DICT_OUT.relative_to(ROOT)} ({len(list(PROCESSED.glob('*.csv')))} datasets)")


def main() -> None:
    if not LEDGER.exists():
        sys.exit("no provenance ledger yet. Run: python run.py data")
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))

    lines = [
        "# Data sources",
        "",
        "<!-- GENERATED by docs/build_docs.py from the fetchers' provenance ledger.",
        "     Do not edit by hand: re-run `python docs/build_docs.py`. -->",
        "",
        "Every processed dataset in this repo, with the URL it came from and the date",
        "it was accessed. Code in this repository is MIT licensed; **each dataset",
        "retains its own publisher's terms**, recorded below.",
        "",
        "| Dataset | Publisher | Coverage | Rows | Accessed | Licence / terms |",
        "|---|---|---|---|---|---|",
    ]
    for name in sorted(ledger):
        e = ledger[name]
        lines.append(
            f"| `{name}` | [{e['publisher']}]({e['url']}) | {e['coverage']} | "
            f"{e['rows']:,} | {e['accessed']} | {e['licence']} |"
        )

    lines += ["", "## Notes and caveats", ""]
    for name in sorted(ledger):
        if ledger[name].get("note"):
            lines.append(f"- **`{name}`** - {ledger[name]['note']}")

    lines += [
        "",
        "## Sources deliberately not used",
        "",
        "- **RBI DBIE** (data.rbi.org.in) - an Angular application with no documented",
        "  public REST API. NIM is derived from filed income statements instead, which",
        "  is more defensible than screen-scraping a portal.",
        "- **data.gov.in** - the public sandbox key authenticates, but filtered resource",
        "  queries time out, and many finance resources have no active API. It would add",
        "  nothing the spine does not already cover.",
        "- **NPCI direct scraping** - npci.org.in serves HTTP 403 to scripted requests.",
        "  Recent months are transcribed from a browser session instead, with per-row",
        "  provenance. See `docs/REFRESH.md`.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(ledger)} datasets)")
    build_dictionary(ledger)


if __name__ == "__main__":
    main()
